from time import sleep
import pygame
pygame.init()
subs = pygame.mixer.Sound("subs.mp3")
subs.play()
print('   ')
print('   ')
print('   ')
print('Rusty: very straightforward')
print('   ')
print('   ')
print('   ')
sleep(3.948)
print('   ')
print('   ')
print('Rusty: if i was going to push you to')
print('be more like... evolved here...')
print('   ')
print('   ')
print('   ')
sleep(3.287)
print('   ')
print('   ')
print("Rusty: i'd ask you to start moving")
print("things into subroutines")
print('   ')
print('   ')
print('   ')
sleep(3.266)
print('   ')
print('   ')
print('   ')
print("Rusty has sent you a URL.")
print('   ')
print('   ')
print('   ')
sleep(3.052)
print('   ')
print('   ')
print('   ')
print("...think...")
print('   ')
print('   ')
print('   ')
sleep(1)
print('   ')
print('   ')
print("...think...")
print('   ')
print('   ')
print('   ')
print('   ')
sleep(1)
print('   ')
print("...think...")
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
sleep(1.138)
print('   ')
print('   ')
print('   ')
print("Dude, what the crap is a subroutine?")
print('   ')
print('   ')
print('   ')
sleep(3.308)
print('   ')
print('   ')
print('   ')
print("He does realize I just started learning Python PERIOD, right?!?!?")
print('   ')
print('   ')
print('   ')
sleep(3.202)
print('   ')
print('   ')
print('   ')
print("Of course he does, but he knows you're a weirdo.")
print('   ')
print('   ')
print('   ')
sleep(3.180)
print('   ')
print('   ')
print('   ')
print("And he knows you're gonna look it up.")
print('   ')
print('   ')
print('   ')
sleep(3.202)
print('   ')
print('   ')
print('   ')
print("And when your brain CPU has enough RAM free,")
print('   ')
print('   ')
print('   ')
sleep(3.201)
print('   ')
print('   ')
print('   ')
print("or whatever the relevant term is called,")
print('   ')
print('   ')
print('   ')
sleep(3.138)
print('   ')
print('   ')
print('   ')
print("You know dang well you're either:")
print('   ')
print('   ')
print('   ')
sleep(3.307)
print('   ')
print('   ')
print("    1: gonna learn what a subroutine is")
print("       and how it works")
print('   ')
print('   ')
print('   ')
sleep(3.308)
print('   ')
print('   ')
print(" or 2: gonna realize you accidentally")
print("       learned it while you were looking up something else.")
print('   ')
print('   ')
print('   ')
sleep(3.223)
print('   ')
print('   ')
print('   ')
print("Case in point:")
print('   ')
print('   ')
print('   ')
sleep(3.202)
print('   ')
print('   ')
print("You didn't know how to work with sleep")
print("and set the line breaks you're using in this code")
print('   ')
print('   ')
print('   ')
sleep(3.223)
print('   ')
print('   ')
print('   ')
print("before Rusty sent you that message.")
print('   ')
print('   ')
print('   ')
sleep(3.223)
print('   ')
print('   ')
print('   ')
print("Neener, neener, neener.")
print('   ')
print('   ')
print('   ')
sleep(3.074)
print('   ')
print('   ')
print('   ')
print("You go, little Padawan.")
print('   ')
print('   ')
sleep(3.266)
print("THE END")
